sudo: required
services:
  - docker

before_install:
  - docker build - sergiomasellis/react-test -f ./client/Dockerfile.dev ./client
  -

script:
  - docker run sergiomasellis/react-test npm test -- --coverage

after_success:
  - docker build -t sergiomasellis/multi-client ./client
  - docker build -t sergiomasellis/multi-nginx ./nginx
  - docker build -t sergiomasellis/multi-server ./server
  - docker build -t sergiomasellis/multi-worker ./worker

  # login to dockerhub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin